### ISSUE TITLE
Question: no operations output

### ISSUE THREAD

**Issue by polomarcus** [Stratio/Sparta#1038]
Hi Stratio team,

I have some trouble using Sparkta, installed on my machine. 
I can see on the Spark monitoring interface (http://localhost:4040/streaming/) that messages are being received, but cannot see the operations output.  Do you mind have a look at my configuration please?

I would like to see the maximum value of the field floorPrice.

``` json
{
  "name": "policy-kafka",
  "description": "Input kafka, output print",
  "sparkStreamingWindow": 2000,
  "checkpointPath": ".",
 "input":
 {
  "name": "in-kafka",
   "type": "Kafka",
   "jarFile": "input-kafka-plugin.jar",
      "configuration": {
        "topics": [{"topic": "auction", "partition" : "1"}],
        "zookeeper.connect": [{"host": "localhost", "port": "2181"}],
        "kafkaParams.group.id": "my-spt-grp"
      }
 },
  "cubes": [
    {
      "name": "testCube",
      "checkpointConfig": {
        "timeDimension": "minute",
        "granularity": "minute",
        "interval": 30000,
        "timeAvailability": 60000
      },
      "dimensions": [
        {
          "field": "exchangeName",
          "name": "exchangeName",
                "configuration": {
                "typeOp": "string"
          }
        },
        {
          "field": "timestamp",
          "name": "timestamp"
        }
      ],
      "operators": [
        {
          "name": "floorPrice",
          "type": "Max",
          "configuration": { "inputField": "floorPrice"}
        }
      ]
    }
  ],
"outputs": [
  {
    "name": "out-print",
    "type": "Print",
    "configuration": {
      "isAutoCalculateId": "false"
    }
  }
]
}
```

15 Messages sent every seconds to the topic "auction" : 

``` json
{  
   "type":"auction",
   "timestamp":"2015-Sep-22 10:37:39.16211",
   "publisherName":"pub4",
   "id":"ibla",
   "name":"testRubicon",
   "exchange":"rubicon",
   "country":"country6",
   "city":"city604",
   "appOrSite":"app",
   "os":"other",
   "floorPrice":0.1,
   "deviceType":"4",
   "creativeSize":"200x360"
}
```

This is the console output for the ./bin/run command: 

```
INFO -2015-09-22 15:05:10,026 -org.apache.spark.Logging$class.logInfo:59 Starting job: foreachRDD at Output.scala:112
INFO -2015-09-22 15:05:10,027 -org.apache.spark.Logging$class.logInfo:59 Registering RDD 19926 (map at Cube.scala:78)
INFO -2015-09-22 15:05:10,027 -org.apache.spark.Logging$class.logInfo:59 Size of output statuses for shuffle 1402 is 155 bytes
INFO -2015-09-22 15:05:10,028 -org.apache.spark.Logging$class.logInfo:59 Size of output statuses for shuffle 1401 is 155 bytes
INFO -2015-09-22 15:05:10,029 -org.apache.spark.Logging$class.logInfo:59 Size of output statuses for shuffle 1400 is 155 bytes
INFO -2015-09-22 15:05:10,029 -org.apache.spark.Logging$class.logInfo:59 Got job 1684 (foreachRDD at Output.scala:112) with 4 output partitions (allowLocal=false)
INFO -2015-09-22 15:05:10,029 -org.apache.spark.Logging$class.logInfo:59 Final stage: ResultStage 7294(foreachRDD at Output.scala:112)
INFO -2015-09-22 15:05:10,029 -org.apache.spark.Logging$class.logInfo:59 Parents of final stage: List(ShuffleMapStage 7290, ShuffleMapStage 7291, ShuffleMapStage 7292, ShuffleMapStage 7293)
INFO -2015-09-22 15:05:10,030 -org.apache.spark.Logging$class.logInfo:59 Missing parents: List(ShuffleMapStage 7290)
INFO -2015-09-22 15:05:10,031 -org.apache.spark.Logging$class.logInfo:59 Submitting ShuffleMapStage 7290 (MapPartitionsRDD[19926] at map at Cube.scala:78), which has no missing parents
INFO -2015-09-22 15:05:10,036 -org.apache.spark.Logging$class.logInfo:59 ensureFreeSpace(7048) called with curMem=47201321, maxMem=1030823608
INFO -2015-09-22 15:05:10,036 -org.apache.spark.Logging$class.logInfo:59 Block broadcast_3150 stored as values in memory (estimated size 6.9 KB, free 938.0 MB)
INFO -2015-09-22 15:05:10,037 -org.apache.spark.Logging$class.logInfo:59 ensureFreeSpace(3798) called with curMem=47208369, maxMem=1030823608
INFO -2015-09-22 15:05:10,038 -org.apache.spark.Logging$class.logInfo:59 Block broadcast_3150_piece0 stored as bytes in memory (estimated size 3.7 KB, free 938.0 MB)
INFO -2015-09-22 15:05:10,038 -org.apache.spark.Logging$class.logInfo:59 Added broadcast_3150_piece0 in memory on localhost:49995 (size: 3.7 KB, free: 978.9 MB)
INFO -2015-09-22 15:05:10,038 -org.apache.spark.Logging$class.logInfo:59 Created broadcast 3150 from broadcast at DAGScheduler.scala:874
INFO -2015-09-22 15:05:10,039 -org.apache.spark.Logging$class.logInfo:59 Submitting 2 missing tasks from ShuffleMapStage 7290 (MapPartitionsRDD[19926] at map at Cube.scala:78)
INFO -2015-09-22 15:05:10,039 -org.apache.spark.Logging$class.logInfo:59 Adding task set 7290.0 with 2 tasks
INFO -2015-09-22 15:05:10,039 -org.apache.spark.Logging$class.logInfo:59 Starting task 0.0 in stage 7290.0 (TID 9311, localhost, NODE_LOCAL, 4089 bytes)
INFO -2015-09-22 15:05:10,039 -org.apache.spark.Logging$class.logInfo:59 Starting task 1.0 in stage 7290.0 (TID 9312, localhost, NODE_LOCAL, 4089 bytes)
INFO -2015-09-22 15:05:10,040 -org.apache.spark.Logging$class.logInfo:59 Running task 0.0 in stage 7290.0 (TID 9311)
INFO -2015-09-22 15:05:10,040 -org.apache.spark.Logging$class.logInfo:59 Running task 1.0 in stage 7290.0 (TID 9312)
INFO -2015-09-22 15:05:10,042 -org.apache.spark.Logging$class.logInfo:59 Partition rdd_19926_0 not found, computing it
INFO -2015-09-22 15:05:10,042 -org.apache.spark.Logging$class.logInfo:59 Found block input-0-1442927108000 locally
INFO -2015-09-22 15:05:10,042 -org.apache.spark.Logging$class.logInfo:59 Partition rdd_19926_1 not found, computing it
INFO -2015-09-22 15:05:10,043 -org.apache.spark.Logging$class.logInfo:59 Found block input-0-1442927109200 locally
INFO -2015-09-22 15:05:10,043 -org.apache.spark.Logging$class.logInfo:59 ensureFreeSpace(1420) called with curMem=47212167, maxMem=1030823608
INFO -2015-09-22 15:05:10,043 -org.apache.spark.Logging$class.logInfo:59 Block rdd_19926_0 stored as bytes in memory (estimated size 1420.0 B, free 938.0 MB)
INFO -2015-09-22 15:05:10,043 -org.apache.spark.Logging$class.logInfo:59 Added rdd_19926_0 in memory on localhost:49995 (size: 1420.0 B, free: 978.9 MB)
INFO -2015-09-22 15:05:10,043 -org.apache.spark.Logging$class.logInfo:59 ensureFreeSpace(1420) called with curMem=47213587, maxMem=1030823608
INFO -2015-09-22 15:05:10,044 -org.apache.spark.Logging$class.logInfo:59 Block rdd_19926_1 stored as bytes in memory (estimated size 1420.0 B, free 938.0 MB)
INFO -2015-09-22 15:05:10,045 -org.apache.spark.Logging$class.logInfo:59 Finished task 0.0 in stage 7290.0 (TID 9311). 1462 bytes result sent to driver
INFO -2015-09-22 15:05:10,045 -org.apache.spark.Logging$class.logInfo:59 Added rdd_19926_1 in memory on localhost:49995 (size: 1420.0 B, free: 978.9 MB)
INFO -2015-09-22 15:05:10,046 -org.apache.spark.Logging$class.logInfo:59 Finished task 0.0 in stage 7290.0 (TID 9311) in 7 ms on localhost (1/2)
INFO -2015-09-22 15:05:10,047 -org.apache.spark.Logging$class.logInfo:59 Finished task 1.0 in stage 7290.0 (TID 9312). 1462 bytes result sent to driver
INFO -2015-09-22 15:05:10,048 -org.apache.spark.Logging$class.logInfo:59 Finished task 1.0 in stage 7290.0 (TID 9312) in 9 ms on localhost (2/2)
INFO -2015-09-22 15:05:10,048 -org.apache.spark.Logging$class.logInfo:59 Removed TaskSet 7290.0, whose tasks have all completed, from pool 
INFO -2015-09-22 15:05:10,054 -org.apache.spark.Logging$class.logInfo:59 ShuffleMapStage 7290 (map at Cube.scala:78) finished in 0.010 s
INFO -2015-09-22 15:05:10,054 -org.apache.spark.Logging$class.logInfo:59 looking for newly runnable stages
INFO -2015-09-22 15:05:10,054 -org.apache.spark.Logging$class.logInfo:59 running: Set(ResultStage 0)
INFO -2015-09-22 15:05:10,055 -org.apache.spark.Logging$class.logInfo:59 waiting: Set(ResultStage 7294)
INFO -2015-09-22 15:05:10,055 -org.apache.spark.Logging$class.logInfo:59 failed: Set()
INFO -2015-09-22 15:05:10,058 -org.apache.spark.Logging$class.logInfo:59 Missing parents for ResultStage 7294: List()
INFO -2015-09-22 15:05:10,058 -org.apache.spark.Logging$class.logInfo:59 Submitting ResultStage 7294 (MapPartitionsRDD[19935] at foreachRDD at Output.scala:112), which is now runnable
INFO -2015-09-22 15:05:10,060 -org.apache.spark.Logging$class.logInfo:59 ensureFreeSpace(13416) called with curMem=47215007, maxMem=1030823608
INFO -2015-09-22 15:05:10,060 -org.apache.spark.Logging$class.logInfo:59 Block broadcast_3151 stored as values in memory (estimated size 13.1 KB, free 938.0 MB)
INFO -2015-09-22 15:05:10,061 -org.apache.spark.Logging$class.logInfo:59 ensureFreeSpace(6490) called with curMem=47228423, maxMem=1030823608
INFO -2015-09-22 15:05:10,061 -org.apache.spark.Logging$class.logInfo:59 Block broadcast_3151_piece0 stored as bytes in memory (estimated size 6.3 KB, free 938.0 MB)
INFO -2015-09-22 15:05:10,061 -org.apache.spark.Logging$class.logInfo:59 Added broadcast_3151_piece0 in memory on localhost:49995 (size: 6.3 KB, free: 978.9 MB)
INFO -2015-09-22 15:05:10,062 -org.apache.spark.Logging$class.logInfo:59 Created broadcast 3151 from broadcast at DAGScheduler.scala:874
INFO -2015-09-22 15:05:10,062 -org.apache.spark.Logging$class.logInfo:59 Submitting 4 missing tasks from ResultStage 7294 (MapPartitionsRDD[19935] at foreachRDD at Output.scala:112)
INFO -2015-09-22 15:05:10,062 -org.apache.spark.Logging$class.logInfo:59 Adding task set 7294.0 with 4 tasks
INFO -2015-09-22 15:05:10,062 -org.apache.spark.Logging$class.logInfo:59 Starting task 0.0 in stage 7294.0 (TID 9313, localhost, PROCESS_LOCAL, 4372 bytes)
INFO -2015-09-22 15:05:10,063 -org.apache.spark.Logging$class.logInfo:59 Starting task 1.0 in stage 7294.0 (TID 9314, localhost, PROCESS_LOCAL, 4372 bytes)
INFO -2015-09-22 15:05:10,063 -org.apache.spark.Logging$class.logInfo:59 Starting task 2.0 in stage 7294.0 (TID 9315, localhost, PROCESS_LOCAL, 4372 bytes)
INFO -2015-09-22 15:05:10,063 -org.apache.spark.Logging$class.logInfo:59 Running task 2.0 in stage 7294.0 (TID 9315)
INFO -2015-09-22 15:05:10,063 -org.apache.spark.Logging$class.logInfo:59 Running task 1.0 in stage 7294.0 (TID 9314)
INFO -2015-09-22 15:05:10,065 -org.apache.spark.Logging$class.logInfo:59 Running task 0.0 in stage 7294.0 (TID 9313)
INFO -2015-09-22 15:05:10,065 -org.apache.spark.Logging$class.logInfo:59 Partition rdd_19929_1 not found, computing it
INFO -2015-09-22 15:05:10,066 -org.apache.spark.Logging$class.logInfo:59 Getting 2 non-empty blocks out of 2 blocks
INFO -2015-09-22 15:05:10,066 -org.apache.spark.Logging$class.logInfo:59 Started 0 remote fetches in 0 ms
INFO -2015-09-22 15:05:10,066 -org.apache.spark.Logging$class.logInfo:59 Found block rdd_19915_1 locally
INFO -2015-09-22 15:05:10,066 -org.apache.spark.Logging$class.logInfo:59 Partition rdd_19929_2 not found, computing it
INFO -2015-09-22 15:05:10,066 -org.apache.spark.Logging$class.logInfo:59 Getting 2 non-empty blocks out of 2 blocks
INFO -2015-09-22 15:05:10,067 -org.apache.spark.Logging$class.logInfo:59 Started 0 remote fetches in 1 ms
INFO -2015-09-22 15:05:10,067 -org.apache.spark.Logging$class.logInfo:59 Found block rdd_19915_2 locally
INFO -2015-09-22 15:05:10,067 -org.apache.spark.Logging$class.logInfo:59 ensureFreeSpace(286) called with curMem=47234913, maxMem=1030823608
INFO -2015-09-22 15:05:10,067 -org.apache.spark.Logging$class.logInfo:59 Block rdd_19929_1 stored as bytes in memory (estimated size 286.0 B, free 938.0 MB)
INFO -2015-09-22 15:05:10,067 -org.apache.spark.Logging$class.logInfo:59 Partition rdd_19929_0 not found, computing it
INFO -2015-09-22 15:05:10,067 -org.apache.spark.Logging$class.logInfo:59 ensureFreeSpace(4) called with curMem=47235199, maxMem=1030823608
INFO -2015-09-22 15:05:10,067 -org.apache.spark.Logging$class.logInfo:59 Added rdd_19929_1 in memory on localhost:49995 (size: 286.0 B, free: 978.9 MB)
INFO -2015-09-22 15:05:10,067 -org.apache.spark.Logging$class.logInfo:59 Getting 2 non-empty blocks out of 2 blocks
INFO -2015-09-22 15:05:10,067 -org.apache.spark.Logging$class.logInfo:59 Block rdd_19929_2 stored as bytes in memory (estimated size 4.0 B, free 938.0 MB)
INFO -2015-09-22 15:05:10,067 -org.apache.spark.Logging$class.logInfo:59 Started 0 remote fetches in 0 ms
INFO -2015-09-22 15:05:10,068 -org.apache.spark.Logging$class.logInfo:59 Added rdd_19929_2 in memory on localhost:49995 (size: 4.0 B, free: 978.9 MB)
INFO -2015-09-22 15:05:10,068 -org.apache.spark.Logging$class.logInfo:59 Finished task 1.0 in stage 7294.0 (TID 9314). 2643 bytes result sent to driver
INFO -2015-09-22 15:05:10,068 -org.apache.spark.Logging$class.logInfo:59 Found block rdd_19915_0 locally
INFO -2015-09-22 15:05:10,068 -org.apache.spark.Logging$class.logInfo:59 Finished task 2.0 in stage 7294.0 (TID 9315). 2643 bytes result sent to driver
INFO -2015-09-22 15:05:10,068 -org.apache.spark.Logging$class.logInfo:59 ensureFreeSpace(4) called with curMem=47235203, maxMem=1030823608
INFO -2015-09-22 15:05:10,068 -org.apache.spark.Logging$class.logInfo:59 Starting task 3.0 in stage 7294.0 (TID 9316, localhost, PROCESS_LOCAL, 4372 bytes)
INFO -2015-09-22 15:05:10,069 -org.apache.spark.Logging$class.logInfo:59 Block rdd_19929_0 stored as bytes in memory (estimated size 4.0 B, free 938.0 MB)
INFO -2015-09-22 15:05:10,069 -org.apache.spark.Logging$class.logInfo:59 Added rdd_19929_0 in memory on localhost:49995 (size: 4.0 B, free: 978.9 MB)
INFO -2015-09-22 15:05:10,069 -org.apache.spark.Logging$class.logInfo:59 Running task 3.0 in stage 7294.0 (TID 9316)
INFO -2015-09-22 15:05:10,069 -org.apache.spark.Logging$class.logInfo:59 Finished task 1.0 in stage 7294.0 (TID 9314) in 6 ms on localhost (1/4)
INFO -2015-09-22 15:05:10,070 -org.apache.spark.Logging$class.logInfo:59 Finished task 2.0 in stage 7294.0 (TID 9315) in 7 ms on localhost (2/4)
INFO -2015-09-22 15:05:10,070 -org.apache.spark.Logging$class.logInfo:59 Finished task 0.0 in stage 7294.0 (TID 9313). 2643 bytes result sent to driver
INFO -2015-09-22 15:05:10,071 -org.apache.spark.Logging$class.logInfo:59 Partition rdd_19929_3 not found, computing it
INFO -2015-09-22 15:05:10,072 -org.apache.spark.Logging$class.logInfo:59 Finished task 0.0 in stage 7294.0 (TID 9313) in 10 ms on localhost (3/4)
INFO -2015-09-22 15:05:10,072 -org.apache.spark.Logging$class.logInfo:59 Getting 2 non-empty blocks out of 2 blocks
INFO -2015-09-22 15:05:10,072 -org.apache.spark.Logging$class.logInfo:59 Started 0 remote fetches in 0 ms
INFO -2015-09-22 15:05:10,073 -org.apache.spark.Logging$class.logInfo:59 Found block rdd_19915_3 locally
INFO -2015-09-22 15:05:10,074 -org.apache.spark.Logging$class.logInfo:59 ensureFreeSpace(286) called with curMem=47235207, maxMem=1030823608
INFO -2015-09-22 15:05:10,074 -org.apache.spark.Logging$class.logInfo:59 Block rdd_19929_3 stored as bytes in memory (estimated size 286.0 B, free 938.0 MB)
INFO -2015-09-22 15:05:10,075 -org.apache.spark.Logging$class.logInfo:59 Added rdd_19929_3 in memory on localhost:49995 (size: 286.0 B, free: 978.9 MB)
INFO -2015-09-22 15:05:10,075 -org.apache.spark.Logging$class.logInfo:59 Finished task 3.0 in stage 7294.0 (TID 9316). 2643 bytes result sent to driver
INFO -2015-09-22 15:05:10,077 -org.apache.spark.Logging$class.logInfo:59 Finished task 3.0 in stage 7294.0 (TID 9316) in 9 ms on localhost (4/4)
INFO -2015-09-22 15:05:10,077 -org.apache.spark.Logging$class.logInfo:59 Removed TaskSet 7294.0, whose tasks have all completed, from pool 
INFO -2015-09-22 15:05:10,078 -org.apache.spark.Logging$class.logInfo:59 ResultStage 7294 (foreachRDD at Output.scala:112) finished in 0.016 s
INFO -2015-09-22 15:05:10,078 -org.apache.spark.Logging$class.logInfo:59 Job 1684 finished: foreachRDD at Output.scala:112, took 0.051439 s
INFO -2015-09-22 15:05:10,078 -org.apache.spark.Logging$class.logInfo:59 Finished job streaming job 1442927110000 ms.0 from job set of time 1442927110000 ms
INFO -2015-09-22 15:05:10,079 -org.apache.spark.Logging$class.logInfo:59 Total delay: 0.078 s for time 1442927110000 ms (execution: 0.062 s)
INFO -2015-09-22 15:05:10,079 -org.apache.spark.Logging$class.logInfo:59 Removing RDD 19917 from persistence list
INFO -2015-09-22 15:05:10,079 -org.apache.spark.Logging$class.logInfo:59 Removing RDD 19916 from persistence list
INFO -2015-09-22 15:05:10,080 -org.apache.spark.Logging$class.logInfo:59 Removing RDD 19916
INFO -2015-09-22 15:05:10,081 -org.apache.spark.Logging$class.logInfo:59 Removing RDD 19917
INFO -2015-09-22 15:05:10,082 -org.apache.spark.Logging$class.logInfo:59 Removing RDD 19787 from persistence list
INFO -2015-09-22 15:05:10,083 -org.apache.spark.Logging$class.logInfo:59 Removing RDD 19787
INFO -2015-09-22 15:05:10,084 -org.apache.spark.Logging$class.logInfo:59 Removing RDD 19500 from persistence list
INFO -2015-09-22 15:05:10,084 -org.apache.spark.Logging$class.logInfo:59 Removing RDD 19500
INFO -2015-09-22 15:05:10,084 -org.apache.spark.Logging$class.logInfo:59 Removing RDD 19499 from persistence list
INFO -2015-09-22 15:05:10,085 -org.apache.spark.Logging$class.logInfo:59 Removing RDD 19499
INFO -2015-09-22 15:05:10,085 -org.apache.spark.Logging$class.logInfo:59 Removing RDD 19498 from persistence list
INFO -2015-09-22 15:05:10,086 -org.apache.spark.Logging$class.logInfo:59 Removing RDD 19498
INFO -2015-09-22 15:05:10,086 -org.apache.spark.Logging$class.logInfo:59 Removing RDD 19497 from persistence list
INFO -2015-09-22 15:05:10,086 -org.apache.spark.Logging$class.logInfo:59 Removing RDD 19497
INFO -2015-09-22 15:05:10,087 -org.apache.spark.Logging$class.logInfo:59 Removing RDD 19496 from persistence list
INFO -2015-09-22 15:05:10,087 -org.apache.spark.Logging$class.logInfo:59 Removing RDD 19496
INFO -2015-09-22 15:05:10,088 -org.apache.spark.Logging$class.logInfo:59 Removing blocks of RDD BlockRDD[19496] at createStream at KafkaInput.scala:41 of time 1442927110000 ms
INFO -2015-09-22 15:05:10,089 -org.apache.spark.Logging$class.logInfo:59 Removed input-0-1442927047800 on localhost:49995 in memory (size: 518.0 B, free: 978.9 MB)
INFO -2015-09-22 15:05:10,090 -org.apache.spark.Logging$class.logInfo:59 Checkpointing graph for time 1442927110000 ms
INFO -2015-09-22 15:05:10,090 -org.apache.spark.Logging$class.logInfo:59 Updating checkpoint data for time 1442927110000 ms
INFO -2015-09-22 15:05:10,091 -org.apache.spark.Logging$class.logInfo:59 Updated checkpoint data for time 1442927110000 ms
INFO -2015-09-22 15:05:10,090 -org.apache.spark.Logging$class.logInfo:59 Removed input-0-1442927048800 on localhost:49995 in memory (size: 518.0 B, free: 978.9 MB)
INFO -2015-09-22 15:05:10,092 -org.apache.spark.Logging$class.logInfo:59 Saving checkpoint for time 1442927110000 ms to file 'file:/opt/sds/sparkta/policy-kafka/checkpoint-1442927110000'
INFO -2015-09-22 15:05:10,095 -org.apache.spark.Logging$class.logInfo:59 Deleting file:/opt/sds/sparkta/policy-kafka/checkpoint-1442927100000
INFO -2015-09-22 15:05:10,095 -org.apache.spark.Logging$class.logInfo:59 Checkpoint for time 1442927110000 ms saved to file 'file:/opt/sds/sparkta/policy-kafka/checkpoint-1442927110000', took 9047 bytes and 3 ms
```

I have tried with the "Print" type output with no results and the CSV one, that gave a CSV with only the fieldnames (exchangeName,timestamp,minute,floorPrice)

Thanks

**Comment by danielcsant** [comment]
Hi!

There is one component that is missing: transformations (http://docs.stratio.com/modules/sparkta/development/policy.html)

This is necessary to model your data and use it on the cubes. It would be also necessary to pass the timestamp in milliseconds format.

The policy would be something like this:

```json
{
  "name": "policy-kafka",
  "description": "Input kafka, output print",
  "sparkStreamingWindow": 2000,
  "checkpointPath": ".",
  "input":
  {
    "name": "in-kafka",
    "type": "Kafka",
    "jarFile": "input-kafka-plugin.jar",
    "configuration": {
      "topics": [{"topic": "auction", "partition" : "1"}],
      "zookeeper.connect": [{"host": "localhost", "port": "2181"}],
      "kafkaParams.group.id": "my-spt-grp"
    }
  },
  "transformations": [
    {
      "name": "morphline",
      "order": 0,
      "outputFields": [
        "floorPrice",
        "timestamp",
        "exchangeName"
      ],
      "type": "Morphlines",
      "configuration": {
        "morphline": {
            "id": "morphline1",
            "importCommands": [
              "org.kitesdk.**"
            ],
            "commands": [
              {
                "readJson": {}
              },
              {
                "extractJsonPaths": {
                  "paths": {
                    "floorPrice": "/floorPrice",
                    "timestamp": "/timestamp",
                    "exchangeName": "/exchange"
                  }
                }
              },
              {
                "removeFields": {
                  "blacklist": [
                    "literal:_attachment_body",
                    "literal:message"
                  ]
                }
              }
            ]
          }
      }
    },
    {
      "name": "date-parser",
      "order": 1,
      "type": "DateTime",
      "inputField": "timestamp",
      "outputFields": [
        "timestamp"
      ],
      "configuration": {
        "inputFormat": "unixMillis"
      }
    }
  ],
  "cubes": [
    {
      "name": "testCube",
      "checkpointConfig": {
        "timeDimension": "minute",
        "granularity": "minute",
        "interval": 30000,
        "timeAvailability": 60000
      },
      "dimensions": [
        {
          "field": "exchangeName",
          "name": "exchangeName",
          "configuration": {
            "typeOp": "string"
          }
        },
        {
          "field": "timestamp",
          "name": "timestamp"
        }
      ],
      "operators": [
        {
          "name": "floorPrice",
          "type": "Max",
          "configuration": { "inputField": "floorPrice"}
        }
      ]
    }
  ],
  "outputs": [
    {
      "name": "out-mongo",
      "type": "MongoDb",
      "configuration": {
        "hosts": [{"host": "localhost" , "port": "27017" }],
        "dbName": "sparkta"
      }
    }
  ]
}
```

Let us know if you have more problems

**Comment by polomarcus** [comment]
Hi @danielcsant,

Thanks for the quick answer, I appreciate.

Unfortunately I am still getting an error : 

```
ERROR-2015-09-23 10:22:13,858 -com.stratio.sparkta.driver.SparktaJob$$anonfun$applyParsers$1.apply:91 Failure[Parser]: [Event, Properties=Map(_attachment_body -> [B@33156d0)] | Message: com.fasterxml.jackson.core.JsonParseException: Unexpected character (':' (code 58)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.ByteArrayInputStream@2650ceaf; line: 1, column: 16] | Parser: MorphlinesParser
org.kitesdk.morphline.api.MorphlineRuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected character (':' (code 58)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.ByteArrayInputStream@2650ceaf; line: 1, column: 16]
	at org.kitesdk.morphline.stdio.AbstractParser.doProcess(AbstractParser.java:98)
	at org.kitesdk.morphline.base.AbstractCommand.process(AbstractCommand.java:156)
	at org.kitesdk.morphline.base.AbstractCommand.doProcess(AbstractCommand.java:181)
	at org.kitesdk.morphline.base.AbstractCommand.process(AbstractCommand.java:156)
	at com.stratio.sparkta.plugin.parser.morphline.MorphlineImpl.process(MorphlinesParser.scala:76)
	at com.stratio.sparkta.plugin.parser.morphline.MorphlinesParser.parse(MorphlinesParser.scala:53)
	at com.stratio.sparkta.driver.SparktaJob$$anonfun$applyParsers$1$$anonfun$6.apply(SparktaJob.scala:86)
	at com.stratio.sparkta.driver.SparktaJob$$anonfun$applyParsers$1$$anonfun$6.apply(SparktaJob.scala:86)
	at scala.util.Try$.apply(Try.scala:161)
	at com.stratio.sparkta.driver.SparktaJob$$anonfun$applyParsers$1.apply(SparktaJob.scala:86)
	at com.stratio.sparkta.driver.SparktaJob$$anonfun$applyParsers$1.apply(SparktaJob.scala:85)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at org.apache.spark.storage.MemoryStore.unrollSafely(MemoryStore.scala:276)
	at org.apache.spark.CacheManager.putInBlockManager(CacheManager.scala:171)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:78)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:242)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:70)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:70)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character (':' (code 58)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.ByteArrayInputStream@2650ceaf; line: 1, column: 16]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:437)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2363)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:794)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:690)
	at com.fasterxml.jackson.databind.MappingIterator.hasNextValue(MappingIterator.java:159)
	at org.kitesdk.morphline.json.ReadJsonBuilder$ReadJson.doProcess(ReadJsonBuilder.java:109)
	at org.kitesdk.morphline.stdio.AbstractParser.doProcess(AbstractParser.java:96)
	... 28 more
```

I am sending this JSON 
```json
{  
   "type":"auction",
   "timestamp":"2015-Sep-22 10:37:39.16211",
   "publisherName":"pub4",
   "id":"ibla",
   "name":"testRubicon",
   "exchange":"rubicon",
   "country":"country6",
   "city":"city604",
   "appOrSite":"app",
   "os":"other",
   "floorPrice":0.1,
   "deviceType":"4",
   "creativeSize":"200x360"
}
```

I also try sending this timestamp "1442996798" but it didn't work.

Tell me if you need more information.

Thanks again

**Comment by Gschiavon** [comment]
Hi @polomarcus,
the timestamp you used in milliseconds its a 1970 date -> Sat Jan 17 1970 17:49:56 GMT+0100 (CET)
You have to try with a current date. 

Let us know if it works!
Thanks.

**Comment by danielcsant** [comment]
Try also to send the event in flat format, I mean, in one line per event instead of indented

**Comment by polomarcus** [comment]
Thanks for your help, data are well generated! I also try with every others operators and it works well, congrats. :+1: 

Can I ask you how do you calculate average? And more precisely, how do you **get previous values** to calculate a new average value?
I've seen this : 
* https://github.com/Stratio/sparkta/blob/54a3b490f84e1eaeaf8cc5f39450311f367ba7e6/plugins/operator-avg/src/main/scala/com/stratio/sparkta/plugin/operator/avg/AvgOperator.scala#L43

But could not figure out how you get the previous values


I have another question about transforming data, if I need to **perform operations on my raw data**, for example add 1 to my floor price, my only option is to use transformations (http://docs.stratio.com/modules/sparkta/development/transformations.html) and http://kitesdk.org/docs/0.11.0/kite-morphlines/morphlinesReferenceGuide.html#/extractJsonPaths. Am I correct?

Thanks

**Comment by danielcsant** [comment]
Hi Paul,

I'll answer over your email

Thanks for your help, data are well generated! I also try with every others
operators and it works well, congrats. [image: :+1:]

Can I ask you how do you calculate average? And more precisely, how do you *get
previous values* to calculate a new average value?
I've seen this :

   -
   https://github.com/Stratio/sparkta/blob/54a3b490f84e1eaeaf8cc5f39450311f367ba7e6/plugins/operator-avg/src/main/scala/com/stratio/sparkta/plugin/operator/avg/AvgOperator.scala#L43

But could not figure out how you get the previous values

We use Spark Streaming to operate over the previous values. This values
depend on the granularity we have selected, so in case we choose a
granurality of minute the operators will work over the values of a minute
in particular. We use the updateStateByKey Spark Streaming function for
this feature.

I have another question about transforming data, if I need to *perform
operations on my raw data*, for example add 1 to my floor price, my only
option is to use transformations (
http://docs.stratio.com/modules/sparkta/development/transformations.html)
and
http://kitesdk.org/docs/0.11.0/kite-morphlines/morphlinesReferenceGuide.html#/extractJsonPaths.
Am I correct?
Transformation would be the best solution.

You can also create your own operator, something like MaxPlusOneOperator.
Operators, dimensions, transformations, input and outputs are pluggable so
you can write custom plugins.

Regards

Daniel Carroza


<http://www.stratio.com/>
Vía de las Dos Castillas, 33, Ática 4, 3ª Planta.
28224 Pozuelo de Alarcón. Madrid.
Tel: +34 91 828 64 73 // *@stratiobd <https://twitter.com/StratioBD>*

2015-09-24 11:39 GMT+02:00 Paul Leclercq <notifications@github.com>:
