### ISSUE TITLE
ClassCastException at parsing timestamp to DateTime

### ISSUE THREAD

**Issue by raulsaeztapia** [Stratio/sparta#1201]
We have detected problems in Sparkta when parsing dimensions fields. On our case the field is **creationDate**. Below you can see an example of a **cube** from our policies:

```
 "cubes": [
    {
      "name": "smf-agg-day",
      "checkpointConfig": {
        "timeDimension": "day",
        "granularity": "day",
        "interval": 30000,
        "timeAvailability": 3600000
      },
      "dimensions": [
        {
          "name": "smfProcess",
          "field": "smfProcess"
        },
        {
          "name": "day",
          "field": "creationDate",
          "type": "DateTime",
          "precision": "day"
        },
        {
          "name": "currency",
          "field": "currency"
        }
      ],
      "operators": [
        {
          "name": "count",
          "type": "Count",
          "configuration": {}
        },
        {
          "name": "sum_amount",
          "type": "Sum",
          "configuration": {
            "inputField": "amount2_value"
          }
        }
      ]
    }
 ]
```

The field was defined with a transformation like this:

```
  "transformations": [
    {
      "name": "morphline",
      "order": 0,
      "type": "Morphlines",
      "outputFields": [
        "smfProcess",
        "creationDate",
        "lastUpdate",
        "amount2_value",
        "currency"
      ],
      "configuration": {
        "morphline": {
          "id": "test1",
          "importCommands": [
            "org.kitesdk.**"
          ],
          "commands": [
            {
              "readJson": {}
            },
            {
              "extractJsonPaths": {
                "paths": {
                  "smfProcess": "/smfProcessType",
                  "creationDate": "/creationDate",
                  "lastUpdate":"/lastUpdate",
                  "amount2_value":"/amount2_value",
                  "currency":"/amount2_currency"
                }
              }
            },
```

And at runtime we got:

```
java.lang.ClassCastException: java.lang.Long cannot be cast to java.util.Date
        at com.stratio.sparkta.plugin.field.datetime.DateTimeField.precisionValue(DateTimeField.scala:58)
        at com.stratio.sparkta.aggregator.CubeOperations$$anonfun$extractDimensionsAggregations$1$$anonfun$1$$anonfun$apply$1.apply(CubeMaker.scala:75)
        at com.stratio.sparkta.aggregator.CubeOperations$$anonfun$extractDimensionsAggregations$1$$anonfun$1$$anonfun$apply$1.apply(CubeMaker.scala:74)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at com.stratio.sparkta.aggregator.CubeOperations$$anonfun$extractDimensionsAggregations$1$$anonfun$1.apply(CubeMaker.scala:74)
        at com.stratio.sparkta.aggregator.CubeOperations$$anonfun$extractDimensionsAggregations$1$$anonfun$1.apply(CubeMaker.scala:73)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
        at com.stratio.sparkta.aggregator.CubeOperations$$anonfun$extractDimensionsAggregations$1.apply(CubeMaker.scala:73)
        at com.stratio.sparkta.aggregator.CubeOperations$$anonfun$extractDimensionsAggregations$1.apply(CubeMaker.scala:71)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at org.apache.spark.storage.MemoryStore.unrollSafely(MemoryStore.scala:249)
        at org.apache.spark.CacheManager.putInBlockManager(CacheManager.scala:172)
        at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:79)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:242)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:68)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:64)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Debugging Sparkta I have seen that **value parameter** is expecting to be a **Date type**:

```
 (precisionKey, DateTimeField.getPrecision(value.asInstanceOf[Date], precisionKey, properties))
```

I would propose a change like this:

```
  @throws(classOf[ClassCastException])
  override def precisionValue(keyName: String, value: JSerializable): (Precision, JSerializable) =
    try {
      val precisionKey = precision(keyName)
      val valueAsType: Date = {
        value match {
          case l: java.lang.Long => new Date(l)
          case d: Date => d
        }
      }
      (precisionKey, DateTimeField.getPrecision(valueAsType, precisionKey, properties))
    }
    catch {
      case cce: ClassCastException => {
        log.error("Error parsing " + value + " .")
        throw cce
      }
    }
}
```

This solution is working for me.

**Comment by compae** [comment]
Hi @raulsaeztapia ,

this issue was solved time ago. The conversions was been included in the companion object TypeOp.scala

Thanks for all
