### ISSUE TITLE
COULD NOT START POLICY.

### ISSUE THREAD

**Issue by haoyixin** [Stratio/Sparta#1627]
2016-08-11 07:42:58 INFO  c.s.s.s.a.h.SpartaHelper$:99 - launched -> sparkStreamingContextActor-tt
2016-08-11 07:42:58 INFO  c.s.s.s.c.p.s.PolicyStatusActor:85 - >> Updating context e1e0d776-0b2b-4204-8017-6c81e79f7238 : <Failed> to <Launched>
2016-08-11 07:42:59 INFO  c.s.s.s.a.a.ClusterLauncherActor:70 - Init new cluster streamingContext with name tt
2016-08-11 07:42:59 WARN  c.s.s.s.c.h.JarsHelper$:81 - The file driver not exists.
2016-08-11 07:42:59 ERROR c.s.s.s.a.a.ClusterLauncherActor:79 - head of empty list
java.util.NoSuchElementException: head of empty list
    at scala.collection.immutable.Nil$.head(List.scala:337) ~[scala-library-2.10.4.jar:na]
    at scala.collection.immutable.Nil$.head(List.scala:334) ~[scala-library-2.10.4.jar:na]
    at com.stratio.sparta.driver.util.ClusterSparkFiles.getDriverFile(ClusterSparkFiles.scala:40) ~[driver-0.10.0.jar:na]
    at com.stratio.sparta.serving.api.actor.ClusterLauncherActor$$anonfun$1.apply$mcV$sp(ClusterLauncherActor.scala:72) ~[serving-api-0.10.0.jar:na]
    at com.stratio.sparta.serving.api.actor.ClusterLauncherActor$$anonfun$1.apply(ClusterLauncherActor.scala:69) ~[serving-api-0.10.0.jar:na]
    at com.stratio.sparta.serving.api.actor.ClusterLauncherActor$$anonfun$1.apply(ClusterLauncherActor.scala:69) ~[serving-api-0.10.0.jar:na]
    at scala.util.Try$.apply(Try.scala:161) ~[scala-library-2.10.4.jar:na]
    at com.stratio.sparta.serving.api.actor.ClusterLauncherActor.doInitSpartaContext(ClusterLauncherActor.scala:69) [serving-api-0.10.0.jar:na]
    at com.stratio.sparta.serving.api.actor.ClusterLauncherActor$$anonfun$receive$1.applyOrElse(ClusterLauncherActor.scala:65) [serving-api-0.10.0.jar:na]
    at akka.actor.Actor$class.aroundReceive(Actor.scala:467) [akka-actor_2.10-2.3.11.jar:na]
    at com.stratio.sparta.serving.api.actor.ClusterLauncherActor.aroundReceive(ClusterLauncherActor.scala:42) [serving-api-0.10.0.jar:na]
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.10-2.3.11.jar:na]
    at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.10-2.3.11.jar:na]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.10-2.3.11.jar:na]
    at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.10-2.3.11.jar:na]
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.10-2.3.11.jar:na]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.10.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.10.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.10.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.10.4.jar:na]
2016-08-11 07:42:59 INFO  c.s.s.s.c.p.s.PolicyStatusActor:85 - >> Updating context e1e0d776-0b2b-4204-8017-6c81e79f7238 : <Launched> to <Failed>

that's logs, and same in standalone or yarn mode T_T

**Comment by skilledmonster** [comment]
@haoyixin - any luck using this github project? Looks like the project is almost dead. Don't see much community help!

**Comment by compae** [comment]
Thanks for the report @haoyixin.

I think that this erros has been generated because is not possible to access to the driverJar file. When you install Sparta this jar is inside the path $SPARTA_HOME/driver, usually the SPARTA_HOME is /opt/sds/sparta. If you want to send cluster jobs with Intellij you must execute mvn clean install before.

@skilledmonster if you think that one project that generate one release per month in July and August and add important features with bugfixing you don't have a good criteria.
Sparta has been deployed in important clients in Spain and is running inside big Spark Clusters with mesos, yarn or standalone

**Comment by compae** [comment]
Any news related to this problem?
