### ISSUE TITLE
Exception instantiating policy socket-policy

### ISSUE THREAD

**Issue by roclas** [Stratio/Sparta#184]
Using this policy:
{
    "name": "socket-policy",
    "duration": 10000,
    "saveRawData": "false",
    "inputs": [
        {
            "name": "in-socket",
            "elementType": "SocketInput",
            "configuration": {
                "hostname": "localhost",
                "port": 9999,
                "storageLevel": "MEMORY_ONLY"
            }
        }
    ],
    "dimensions": [
        {
            "dimensionType": "PassthroughBucketer",
            "name": "word"
        },
        {
            "dimensionType": "PassthroughBucketer",
            "name": "wordCount"
        }
    ],
    "rollups": [
        {
            "dimensionAndBucketTypes": [
                {
                    "dimensionName": "word",
                    "bucketType": "identity"
                },
        {
                    "dimensionName": "wordCount",
                    "bucketType": "identity"
                }

```
        ]
    }
],
"outputs": [
  {
 "name": "out-print",
  "elementType": "PrintOutput",
  "configuration": {}
  }
],
"operators": [
    {
        "name": "count-operator",
        "elementType": "CountOperator",
        "configuration": {}
    }
],
"parsers": [
    {
        "name": "morphline-parser",
        "elementType": "MorphlinesParser",
        "configuration": {
            "morphline": {
                "id": "morphline1",
                "importCommands": [
                    "org.kitesdk.**",
                    "com.stratio.ingestion.morphline.**"
                ],
                "commands": [
                    {
                        "readJson": {}
                    },
                    {
                        "extractJsonPaths": {
                            "paths": {
                                "word": "/word",
                                "wordCount": "/wordCount"
                            }
                        }
                    },
                    {
                        "removeFields": {
                            "blacklist": [
                                "literal:_attachment_body"
                            ]
                        }
                    }
                ]
            }
        }
    }
]
```

}

I get this error

HOT-plugin.jar with timestamp 1432283933834
ERROR StreamingContextActor - Exception instantiating policy socket-policy
java.io.FileNotFoundException: File file:/opt/sds/sparkta/checkpoint/90b710cc-7950-400a-b3c0-1b552e4811fd does not exist
    at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:520)
    at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:398)
    at org.apache.spark.SparkContext$$anonfun$setCheckpointDir$1.apply(SparkContext.scala:1635)
    at org.apache.spark.SparkContext$$anonfun$setCheckpointDir$1.apply(SparkContext.scala:1631)
    at scala.Option.map(Option.scala:145)
    at org.apache.spark.SparkContext.setCheckpointDir(SparkContext.scala:1631)
    at org.apache.spark.streaming.StreamingContext.checkpoint(StreamingContext.scala:216)
    at com.stratio.sparkta.driver.factory.SparkContextFactory$.sparkStreamingInstance(SparkContextFactory.scala:53)
    at com.stratio.sparkta.driver.service.StreamingContextService.createStreamingContext(StreamingContextService.scala:49)
    at com.stratio.sparkta.driver.actor.StreamingContextActor$$anonfun$receive$1$$anonfun$2.apply(StreamingContextActor.scala:44)
    at com.stratio.sparkta.driver.actor.StreamingContextActor$$anonfun$receive$1$$anonfun$2.apply(StreamingContextActor.scala:44)
    at scala.util.Try$.apply(Try.scala:161)
    at com.stratio.sparkta.driver.actor.StreamingContextActor$$anonfun$receive$1.applyOrElse(StreamingContextActor.scala:44)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
    at com.stratio.sparkta.driver.actor.InstrumentedActor.aroundReceive(InstrumentedActor.scala:24)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
    at akka.actor.ActorCell.invoke(ActorCell.scala:487)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
    at akka.dispatch.Mailbox.run(Mailbox.scala:220)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
ERROR SupervisorActor - Error initializing StreamingContext with name: socket-policy
java.io.FileNotFoundException: File file:/opt/sds/sparkta/checkpoint/90b710cc-7950-400a-b3c0-1b552e4811fd does not exist
    at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:520)
    at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:398)
    at org.apache.spark.SparkContext$$anonfun$setCheckpointDir$1.apply(SparkContext.scala:1635)
    at org.apache.spark.SparkContext$$anonfun$setCheckpointDir$1.apply(SparkContext.scala:1631)
    at scala.Option.map(Option.scala:145)
    at org.apache.spark.SparkContext.setCheckpointDir(SparkContext.scala:1631)
    at org.apache.spark.streaming.StreamingContext.checkpoint(StreamingContext.scala:216)
    at com.stratio.sparkta.driver.factory.SparkContextFactory$.sparkStreamingInstance(SparkContextFactory.scala:53)
    at com.stratio.sparkta.driver.service.StreamingContextService.createStreamingContext(StreamingContextService.scala:49)
    at com.stratio.sparkta.driver.actor.StreamingContextActor$$anonfun$receive$1$$anonfun$2.apply(StreamingContextActor.scala:44)
    at com.stratio.sparkta.driver.actor.StreamingContextActor$$anonfun$receive$1$$anonfun$2.apply(StreamingContextActor.scala:44)
    at scala.util.Try$.apply(Try.scala:161)
    at com.stratio.sparkta.driver.actor.StreamingContextActor$$anonfun$receive$1.applyOrElse(StreamingContextActor.scala:44)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
    at com.stratio.sparkta.driver.actor.InstrumentedActor.aroundReceive(InstrumentedActor.scala:24)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
    at akka.actor.ActorCell.invoke(ActorCell.scala:487)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
    at akka.dispatch.Mailbox.run(Mailbox.scala:220)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
WARN  StreamingContextActor - Unrecognized StreamingContext to stop!
WARN  StreamingContextActor - Shutting down com.stratio.sparkta.driver.actor.StreamingContextActor

**Comment by danielcsant** [comment]
This error is thrown when running Sparkta from a deb/rpm installation.

**Comment by arinconstrio** [comment]
The problem is the following , spaRkTA hasn't got enough privileges to write the checkpoint files, there are two feasible solutions, 
1.- execute as sudo or root "$SPARKTA_HOME/sudo bin/run"
2.- set the checkpoint dir in the policy json pointing where you have permission to write
