### ISSUE TITLE
Job aborted due to stage failure

### ISSUE THREAD

**Issue by elenapascual** [Stratio/Sparta#413]
Hello!
This came up when running sparkta-spark1.3 and processing 86.000 events. Sparkta was launched by root

*ERROR JobScheduler - Error running job streaming job 1436519460000 ms.0
org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 5.0 failed 1 times, most recent failure: Lost task 1.0 in stage 5.0 (TID 4, localhost): java.io.IOException: Failed to create local dir in /tmp/spark-0c463f24-e058-4fb6-b211-438228b962fa/blockmgr-11ab4a0d-f35e-4f3a-8852-f0814ff44476/30.
    at org.apache.spark.storage.DiskBlockManager.getFile(DiskBlockManager.scala:73)
    at org.apache.spark.storage.DiskBlockManager.getFile(DiskBlockManager.scala:84)
    at org.apache.spark.storage.DiskBlockManager.createTempShuffleBlock(DiskBlockManager.scala:117)
    at org.apache.spark.util.collection.ExternalSorter$$anonfun$spillToPartitionFiles$1.apply(ExternalSorter.scala:359)
    at org.apache.spark.util.collection.ExternalSorter$$anonfun$spillToPartitionFiles$1.apply(ExternalSorter.scala:355)
    at scala.Array$.fill(Array.scala:267)
    at org.apache.spark.util.collection.ExternalSorter.spillToPartitionFiles(ExternalSorter.scala:355)
    at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:211)
    at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
    at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:68)
    at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
    at org.apache.spark.scheduler.Task.run(Task.scala:64)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
    at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1203)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1192)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1191)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1191)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:693)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:693)
    at scala.Option.foreach(Option.scala:236)
    at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:693)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1393)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1354)
    at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)*

Thanks for your help!

**Comment by danielcsant** [comment]
Hi,

Could you try to create that path manually? (/tmp/spark-0c463f24-e058-4fb6-b211-438228b962fa/blockmgr-11ab4a0d-f35e-4f3a-8852-f0814ff44476/30)

It is created normally?

**Comment by elenapascual** [comment]
Hello,

I can create the directory and the file with authorized root access but I
can't access the directory.

Permitted:
sudo mkdir /tmp/spark-0c463f24-e058-4fb6-b211-438228b962fa/
blockmgr-11ab4a0d-f35e-4f3a-8852-f0814ff44476/
sudo vim /tmp/spark-0c463f24-e058-4fb6-b211-438228b962fa/
blockmgr-11ab4a0d-f35e-4f3a-8852-f0814ff44476/30

Not Permitted:
cd /tmp/spark-0c463f24-e058-4fb6-b211-438228b962fa/

Do I need to be root??

Elena.



2015-07-10 11:40 GMT+02:00 Daniel Carroza Santana <notifications@github.com>
:

**Comment by danielcsant** [comment]
Yes, you would need to be root.

Run Sparkta without being root. It seems it is a permission issue

**Comment by elenapascual** [comment]
Fixed!
That was the problem. I first changed the path for the checkpoint directory in the policy because the old dir needed root permissions. By setting the checkpoint dir inside a dir that doesn't need root permissions and running sparkta as a normal user I got no errors.

Thanks a lot for your help!

**Comment by sumitnigam** [comment]
I am facing the same issue. However, in my case the inability to create local file comes up quite randomly and succeeds most of the time:

15/08/17 10:07:52 INFO spark.SparkEnv: Registering BlockManagerMaster
15/08/17 10:07:52 INFO storage.DiskBlockManager: Created local directory at /tmp/spark-891142e8-e3a4-4405-8fc7-e1ab34cb362e/blockmgr-2cd58b1a-8eb6-4af3-ae18-eaea8fc5c30b

But just a bit later, upon restart:

15/08/17 10:13:02 INFO scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
15/08/17 10:13:02 INFO spark.SparkContext: Successfully stopped SparkContext
15/08/17 10:13:02 ERROR impl.IngestDriverServiceImpl: Job aborted due to stage failure: Task serialization failed: java.io.IOException: Failed to create local dir in /tmp/spark-891142e8-e3a4-4405-8fc7-e1ab34cb362e/blockmgr-2cd58b1a-8eb6-4af3-ae18-eaea8fc5c30b/25.
org.apache.spark.storage.DiskBlockManager.getFile(DiskBlockManager.scala:73)
