### ISSUE TITLE
elasticsearch no nodes available

### ISSUE THREAD

**Issue by elenapascual** [Stratio/Sparta#435]
Sparkta version: versions/sparkta-with-spark-1.3
Elastisearch: 1.5.2

When both are in the same machine there is no problem. However, when they are in different machines within the same cluster the following error comes up:

ERROR StreamingContextActor - Exception instantiating policy *****************
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
    at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:298)
    at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:214)
    at org.elasticsearch.client.transport.support.InternalTransportIndicesAdminClient.execute(InternalTransportIndicesAdminClient.java:85)
    at org.elasticsearch.client.support.AbstractIndicesAdminClient.create(AbstractIndicesAdminClient.java:249)
    at com.sksamuel.elastic4s.ElasticClient$$anonfun$execute$16.apply(Client.scala:146)
    at com.sksamuel.elastic4s.ElasticClient$$anonfun$execute$16.apply(Client.scala:146)
    at com.sksamuel.elastic4s.ElasticClient.injectFuture(Client.scala:340)
    at com.sksamuel.elastic4s.ElasticClient.execute(Client.scala:146)
    at com.stratio.sparkta.plugin.output.elasticsearch.ElasticSearchOutput.com$stratio$sparkta$plugin$output$elasticsearch$ElasticSearchOutput$$createIndexAcordingToSchema(ElasticSearchOutput.scala:84)
    at com.stratio.sparkta.plugin.output.elasticsearch.ElasticSearchOutput$$anonfun$createIndices$2.apply(ElasticSearchOutput.scala:78)
    at com.stratio.sparkta.plugin.output.elasticsearch.ElasticSearchOutput$$anonfun$createIndices$2.apply(ElasticSearchOutput.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at com.stratio.sparkta.plugin.output.elasticsearch.ElasticSearchOutput.createIndices(ElasticSearchOutput.scala:76)
    at com.stratio.sparkta.plugin.output.elasticsearch.ElasticSearchOutput.setup(ElasticSearchOutput.scala:73)
    at com.stratio.sparkta.sdk.Output.persist(Output.scala:77)
    at com.stratio.sparkta.driver.service.StreamingContextService$$anonfun$createStreamingContext$1.apply(StreamingContextService.scala:83)
    at com.stratio.sparkta.driver.service.StreamingContextService$$anonfun$createStreamingContext$1.apply(StreamingContextService.scala:83)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at com.stratio.sparkta.driver.service.StreamingContextService.createStreamingContext(StreamingContextService.scala:83)
    at com.stratio.sparkta.driver.actor.StreamingContextActor$$anonfun$receive$1$$anonfun$2.apply(StreamingContextActor.scala:44)
    at com.stratio.sparkta.driver.actor.StreamingContextActor$$anonfun$receive$1$$anonfun$2.apply(StreamingContextActor.scala:44)
    at scala.util.Try$.apply(Try.scala:161)
    at com.stratio.sparkta.driver.actor.StreamingContextActor$$anonfun$receive$1.applyOrElse(StreamingContextActor.scala:44)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
    at com.stratio.sparkta.driver.actor.InstrumentedActor.aroundReceive(InstrumentedActor.scala:24)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
    at akka.actor.ActorCell.invoke(ActorCell.scala:487)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
    at akka.dispatch.Mailbox.run(Mailbox.scala:220)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
ERROR StreamingActor - Error initializing StreamingContext with name: agg_proc_minute
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
    at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:298)
    at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:214)
    at org.elasticsearch.client.transport.support.InternalTransportIndicesAdminClient.execute(InternalTransportIndicesAdminClient.java:85)
    at org.elasticsearch.client.support.AbstractIndicesAdminClient.create(AbstractIndicesAdminClient.java:249)
    at com.sksamuel.elastic4s.ElasticClient$$anonfun$execute$16.apply(Client.scala:146)
    at com.sksamuel.elastic4s.ElasticClient$$anonfun$execute$16.apply(Client.scala:146)
    at com.sksamuel.elastic4s.ElasticClient.injectFuture(Client.scala:340)
    at com.sksamuel.elastic4s.ElasticClient.execute(Client.scala:146)
    at com.stratio.sparkta.plugin.output.elasticsearch.ElasticSearchOutput.com$stratio$sparkta$plugin$output$elasticsearch$ElasticSearchOutput$$createIndexAcordingToSchema(ElasticSearchOutput.scala:84)
    at com.stratio.sparkta.plugin.output.elasticsearch.ElasticSearchOutput$$anonfun$createIndices$2.apply(ElasticSearchOutput.scala:78)
    at com.stratio.sparkta.plugin.output.elasticsearch.ElasticSearchOutput$$anonfun$createIndices$2.apply(ElasticSearchOutput.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at com.stratio.sparkta.plugin.output.elasticsearch.ElasticSearchOutput.createIndices(ElasticSearchOutput.scala:76)
    at com.stratio.sparkta.plugin.output.elasticsearch.ElasticSearchOutput.setup(ElasticSearchOutput.scala:73)
    at com.stratio.sparkta.sdk.Output.persist(Output.scala:77)
    at com.stratio.sparkta.driver.service.StreamingContextService$$anonfun$createStreamingContext$1.apply(StreamingContextService.scala:83)
    at com.stratio.sparkta.driver.service.StreamingContextService$$anonfun$createStreamingContext$1.apply(StreamingContextService.scala:83)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at com.stratio.sparkta.driver.service.StreamingContextService.createStreamingContext(StreamingContextService.scala:83)
    at com.stratio.sparkta.driver.actor.StreamingContextActor$$anonfun$receive$1$$anonfun$2.apply(StreamingContextActor.scala:44)
    at com.stratio.sparkta.driver.actor.StreamingContextActor$$anonfun$receive$1$$anonfun$2.apply(StreamingContextActor.scala:44)
    at scala.util.Try$.apply(Try.scala:161)
    at com.stratio.sparkta.driver.actor.StreamingContextActor$$anonfun$receive$1.applyOrElse(StreamingContextActor.scala:44)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
    at com.stratio.sparkta.driver.actor.InstrumentedActor.aroundReceive(InstrumentedActor.scala:24)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
    at akka.actor.ActorCell.invoke(ActorCell.scala:487)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
    at akka.dispatch.Mailbox.run(Mailbox.scala:220)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Any leads?

Thank you!

**Comment by danielcsant** [comment]
Please, check all nodes view each other. They must resolve the FQDN in their /etc/hosts.

Does this solve the problem?

**Comment by elenapascual** [comment]
I am sorry I forgot to mention  in my previous post that I can telnet from the spakta machine to the ES machine. They both see each other.
My cluster is just five nodes where one is for sparkta and another one for ES.
