### ISSUE TITLE
Yarn cluster mode is not working

### ISSUE THREAD

**Issue by sgomezg** [Stratio/Sparta#883]
Cluster execution on YARN is not working. Error:

```
15/09/14 17:44:06 ERROR driver.SparktaJob$: String: 1: backslash followed by 'c', this is not a valid escape sequence (quoted strings use JSON escaping, so use double-backslash \\ for literal backslash)
com.typesafe.config.ConfigException$Parse: String: 1: backslash followed by 'c', this is not a valid escape sequence (quoted strings use JSON escaping, so use double-backslash \\ for literal backslash)
    at com.typesafe.config.impl.Parser$ParseContext.nextToken(Parser.java:279)
    at com.typesafe.config.impl.Parser$ParseContext.nextTokenIgnoringNewline(Parser.java:302)
    at com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:735)
    at com.typesafe.config.impl.Parser$ParseContext.parseValue(Parser.java:520)
    at com.typesafe.config.impl.Parser$ParseContext.parse(Parser.java:979)
    at com.typesafe.config.impl.Parser.parse(Parser.java:34)
    at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:222)
    at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:210)
    at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:176)
    at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:170)
    at com.typesafe.config.impl.Parseable.parse(Parseable.java:227)
    at com.typesafe.config.ConfigFactory.parseString(ConfigFactory.java:823)
    at com.typesafe.config.ConfigFactory.parseString(ConfigFactory.java:827)
    at com.stratio.sparkta.driver.SparktaClusterJob$.initSparktaConfig(SparktaClusterJob.scala:88)
    at com.stratio.sparkta.driver.SparktaClusterJob$$anonfun$2.apply(SparktaClusterJob.scala:50)
    at com.stratio.sparkta.driver.SparktaClusterJob$$anonfun$2.apply(SparktaClusterJob.scala:48)
    at scala.util.Try$.apply(Try.scala:161)
    at com.stratio.sparkta.driver.SparktaClusterJob$.main(SparktaClusterJob.scala:48)
    at com.stratio.sparkta.driver.SparktaClusterJob.main(SparktaClusterJob.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:483)
```

Malformed parameters:

```
ee390f5a-8ab3-4fc8-8c1d-b2ccd5b9fd0f
/user/sgomezg/twitter-parquet-1-ee390f5a-8ab3-4fc8-8c1d-b2ccd5b9fd0f/plugins/
/user/sgomezg/twitter-parquet-1-ee390f5a-8ab3-4fc8-8c1d-b2ccd5b9fd0f/classpath/
"\zk\:{\connectionString\:\localhost:2181\,\connectionTimeout\:15000,\retryAttempts\:5,\retryInterval\:10000,\sessionTimeout\:60000}"
"\config\:{\executionMode\:\yarn\,\rememberPartitioner\:true,\stopGracefully\:true}"
```

YARN's execution is removing double quotes

**Comment by sgomezg** [comment]
```
15/09/15 16:26:57 INFO yarn.ApplicationMaster: Final app status: SUCCEEDED, exitCode: 0, (reason: Shutdown hook called before final status was reported.)
Uncaught error from thread [7a8751f3-0f38-47c3-8177-1beab665133a-akka.actor.default-dispatcher-6] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[7a8751f3-0f38-47c3-8177-1beab665133a]
java.lang.NoClassDefFoundError: org/json4s/ext/EnumNameSerializer
	at com.stratio.sparkta.serving.core.models.SparktaSerializer$class.$init$(SparktaSerializer.scala:31)
	at com.stratio.sparkta.serving.core.policy.status.PolicyStatusActor.<init>(PolicyStatusActor.scala:30)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at akka.util.Reflect$.instantiate(Reflect.scala:45)
	at akka.actor.NoArgsReflectConstructor.produce(Props.scala:361)
	at akka.actor.Props.newActor(Props.scala:252)
	at akka.actor.ActorCell.newActor(ActorCell.scala:552)
	at akka.actor.ActorCell.create(ActorCell.scala:578)
	at akka.actor.dungeon.FaultHandling$class.finishCreate(FaultHandling.scala:136)
	at akka.actor.dungeon.FaultHandling$class.faultCreate(FaultHandling.scala:130)
	at akka.actor.ActorCell.faultCreate(ActorCell.scala:369)
	at akka.actor.dungeon.FaultHandling$class.faultRecreate(FaultHandling.scala:59)
	at akka.actor.ActorCell.faultRecreate(ActorCell.scala:369)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:459)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by sgomezg** [comment]
[Current code] (https://github.com/sgomezg/sparkta/tree/bugfix/yarn-execution)
